### ISSUE TITLE
When BirdNET-Pi ignores a detection even though it is above the confidence threshold, it should say _why_.

### ISSUE THREAD

**Issue by Nachtzuster** [Nachtzuster/BirdNET-Pi#138]
This is usually due to the  Species range model excluding the species.
It could take a while before people figure that out and can take action.

See
https://github.com/Nachtzuster/BirdNET-Pi/discussions/106
https://github.com/Nachtzuster/BirdNET-Pi/discussions/117
From the original BirdNET:
https://github.com/mcguirepr89/BirdNET-Pi/discussions/967

I'm sure there's plenty more

Maybe just a warning in the log?

**Comment by alexbelgium** [comment]
Hi, I've made a PR proposal. It seems to work on my system. Sidenote, I wonder if we shouldn't color log.warning messages in orange to make them be a bit more visible.

**Comment by Nachtzuster** [comment]
thanks @alexbelgium
