### ISSUE TITLE
Species Stats page not working

### ISSUE THREAD

**Issue by dalogue1** [Nachtzuster/BirdNET-Pi#150]
The Species Stats page does not provide any information.  This worked before and now it does not.  I have two systems and they both just have no table of information. They are both up to date with the latest version. 

![image](https://github.com/user-attachments/assets/434b3853-dc6d-4289-a521-e6b064e4becb)

**Comment by Nachtzuster** [comment]
Check if it is running? Tools->Services

**Comment by dalogue1** [comment]
It works.
