### ISSUE TITLE
Singular of Species is Species

### ISSUE THREAD

**Issue by dalogue1** [Nachtzuster/BirdNET-Pi#156]
It is just a nitpick but the singular of Species is Species.  Can the Advanced Settings page please be corrected to say "species" instead of "specie" under Disk Management?

![image](https://github.com/user-attachments/assets/edd6911c-0cc8-49e0-9e5f-ce283c24fbab)

![image](https://github.com/user-attachments/assets/163d96d9-32c5-43ba-a8ab-8a31304a6373)

**Comment by Nachtzuster** [comment]
Thanks!
