### ISSUE TITLE
Misspelling under Model on Settings page

### ISSUE THREAD

**Issue by dalogue1** [Nachtzuster/BirdNET-Pi#162]
Occurrence has two R's

![image](https://github.com/user-attachments/assets/a892153c-f3d3-401d-b507-c48311fdba12)

![image](https://github.com/user-attachments/assets/458e8245-954b-47dc-9f47-7c3f5b5f8612)

![image](https://github.com/user-attachments/assets/58cf1268-cd9f-4bc6-8863-eb10826e4e52)

**Comment by Emmo213** [comment]
Those are easy fixes. Pull request opened.

**Comment by lloydbayley** [comment]
Blimey...we're proving spelling now?!

**Comment by lloydbayley** [comment]
see what I did therE?

**Comment by Nachtzuster** [comment]
@Emmo213 @dalogue1 thanks!
