### ISSUE TITLE
Wrong latin name on Common Starling recordings

### ISSUE THREAD

**Issue by Hiemstra87** [Nachtzuster/BirdNET-Pi#196]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**
All my Common Starling (Sturnus vulgaris) recordings get the scientific name for Daurian Starling (Agropsar sturninus). (Dutch name is correct though)

I don't know if this is something that can be fixed in the BirdNET application or if this is wrong in the TFlite.

**Screenshots**

</details>

**Comment by alexbelgium** [comment]
Have you updated to latest? It would have supposed to be solved by https://github.com/Nachtzuster/BirdNET-Pi/pull/187

**Comment by Hiemstra87** [comment]
Ah, silly me. Haven't noticed that issue. Fixed with the update indeed. Thanks for the quick response.
