### ISSUE TITLE
Cancelling update still updates

### ISSUE THREAD

**Issue by craigusus** [Nachtzuster/BirdNET-Pi#236]
**Describe the bug**
When I click on the cancel button, if I have clicked on Update by mistake, the update still goes ahead and updates

**To Reproduce**
1. Go to 'Tools > System Controls'
2. Click on 'Update'
3. Click on 'Cancel'
4. Updates continue

**Expected behavior**
To cancel and not update.

**Screenshots**
<img width="224" alt="{DB074F38-4BF4-4FDB-A9C0-F44797FF306C}" src="https://github.com/user-attachments/assets/ea89610b-9a11-4786-8b83-5110a567c02a">

**Your build**
Raspberry Pi 5 8GB. 
Running version: 5257f326fa37090a7f5d859d7cde19ac0153b914

**Comment by Nachtzuster** [comment]
Thanks for reporting!
Looks like this issue has been in there since august 2022 :smile: 

Should be fixed now
