### ISSUE TITLE
Weekly Report (yes, it's still not working) bug

### ISSUE THREAD

**Issue by MueJosh** [Nachtzuster/BirdNET-Pi#26]
In the settings menu for Apprise notification there is a problem with the weekly report. 
It doesn't get send (this is also problem in the original repo) 

**To Reproduce**
1. Go to `Tools` - `Settings` - `Notifications`
2. Click on `send weekly report`
3. Error - Don't see a weekly report at the end/ start of the week ;) 

**Expected behavior**
Get the weekly report as an notification from apprise

**Screenshots**
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/a494b9e1-4364-4439-bf07-a3d1f2886f7f)

**Your build**
Raspberry Pi 4
64 bit bullseye lite

**Code or log snippets**

### I think the problem lays in this script: 

> https://github.com/Nachtzuster/BirdNET-Pi/blob/main/scripts/weekly_report.sh

As Its says that the user is named Birdnet-pi and it should be the real username not the default one. 

I can't test it right now but maybe you can get it working.

**Comment by Nachtzuster** [comment]
No, that is the directory name in $HOME, and that is ok.

There might be something wrong with your specific setup:
Could you post Tools->System Info->Viewer ?

**Comment by MueJosh** [comment]
> No, that is the directory name in $HOME, and that is ok.
> 
> 
> 
> There might be something wrong with your specific setup:
> 
> Could you post Tools->System Info->Viewer ?

Sure, here it is :) 

![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/abbf1811-438e-4bc3-be29-7ce3ab4dfd71)
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/465f91cb-6047-4708-be79-43cd615f2628)
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/f9bf8872-3114-4bc5-b16f-87485132bda3)
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/3f16e7d2-efe8-4c71-9570-0abaa3b145eb)

**Comment by Nachtzuster** [comment]
that looks ok -I think-

Could you run `/usr/local/bin/weekly_report.sh`  manually ? and report the output?
Does that give you a notification?

**Comment by MueJosh** [comment]
Yeah, I wasted a lot of time trying to get it running. In the end I gave up (though I would love too see it working) 

![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/bca4f17b-8eaf-4ddc-a12f-ad63d2c914f2)

#### And the notification: 
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/d6f4dfb7-d36b-416d-8996-3ca546596901)

**Comment by Nachtzuster** [comment]
@MueJosh help me understand the issue you're seeing is that 
1) you do not get any weekly notifications or
2) the notification you get are a stack-trace like shown in your screenshot
3) something else

**Comment by MueJosh** [comment]
1) Yes, I don't receive a weekly report (though I'm receiving detections etc.) 

2) yep, but I just receive this notification (like in the screenshot) if I send a "test notification" 


I don't even know how the weekly report should look like, is it a picture of the weekly_report.php or plain text? 
I have never seen it before 😅

**Comment by Nachtzuster** [comment]
looking at the screenshot, I think you're seeing a division by zero issue.
I pushed a fix to handle that safely.

Could you run `/usr/local/bin/weekly_report.sh` again?
Does that give you a notification now?

**Comment by MueJosh** [comment]
Now it gives me nothing 
Normal bird notifications still work 


Updated, reboot, checked the files, checked apprise notifications (saved it again, no changes done)

It always gives me this output (tried sudo once) 
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/bde5ac4a-081d-450d-80ef-ee8809193ab6)

Really confusing, maybe it's because of the telegram api (idk)

**Comment by Nachtzuster** [comment]
This could actually be progress :-)

could you see what `http://[YOURPI]/views.php?view=Weekly%20Report&ascii=true`
gives you, that should be the report

**Comment by MueJosh** [comment]
That's nice to hear ^^

![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/42b39dff-3c05-4d47-8708-e91333ec32db)

**Comment by Nachtzuster** [comment]
Ah yes, looking good. :+1: 
So now the week report itself is working.

I'm not sure about the apprise error though...
Could you remove one of the apprise entries so it should send one single notification and then run
`/usr/local/bin/weekly_report.sh` agiain? _no sudo_

**Comment by Nachtzuster** [comment]
hmm, some googling sugests that this could be a Telegram limitation.
similar issue: https://github.com/Eleirbag89/TelegramBotPHP/issues/152

Could you test with another serivice like email oe whatsapp to confirm?

**Comment by MueJosh** [comment]
I got fed up with the notifications / weekly report ;) 

Signal needs a docker / server to send messages, email needs the password (I have 2fa enabled- more issues) 
This is why I use telegram 😅 

Problem are all the <>*/ ... on the weekly report 
Adding `?format=markdown` to the chat id "solves" the problem. 
Not great but it works! 

![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/77d21383-3cd2-4524-9ec3-0c24655b1106)
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/b8eaffa5-df49-4a87-8b09-eb530c5e25ba)

[pull request (never did this before; it took some time to figure it out)](https://github.com/Nachtzuster/BirdNET-Pi/pull/30)

**Comment by Nachtzuster** [comment]
That is a great find! Seems the best solution I think

**Comment by arne1921KF** [comment]
Nice, thank you, @MueJosh.

Interestingly, adding the `?format=markdown` command breaks the formatting of the notification title. 

OTH, it allows formatting for the body, which is great. Having scientific names in _italics_ is such a relief... ;-)
The only thing missing (from markdown, so no solution for that) is the ability to add a new line.

Here's my current take:
`*$comname* (_$sciname_) wurde erkannt. `Confidence score: $confidence, $confidencepct %, cutoff: $cutoff, sensitivity: $sens` [Audio available on local network]($listenurl)`

**Comment by MueJosh** [comment]
@Nachtzuster should I open another issue for notification breaks?
I don't mind Handeling it here

Example, this is how it's set up normally:
`Ein/e $comname  ($sciname)  wurde soeben erkannt. Erkennungswahrscheinlichkeit $confidencepct% `
Looks like this: 
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/465451fa-723d-424a-a813-00e3aba5b153)


Code for break-line <> , /n , %0A or whatever the server wants for a break
`Ein/e $comname  ($sciname)  wurde soeben erkannt. %0AErkennungswahrscheinlichkeit $confidencepct%`

This is how it's supposed to look like (send with "test notification" button)
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/9e1f7ad9-1e4e-43a4-af3f-bb401e5b2c06)



Same break line `%0A`
How it actually comes out: 
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/ea2d47fa-6f95-4d87-baf7-8ef2c1d2e5d5)


If I have the time (can be weeks to months) I can handle it. 

Maybe it's an issue with apprise? (I don't think so)

**Comment by Nachtzuster** [comment]
> should I open another issue for notification breaks?

yes please.

**Comment by Nachtzuster** [comment]
@MueJosh I've swapped out the `<small>` tags in the html, it still looks the same as before -kinda- but now sending to Telegram should work without workaround.
