### ISSUE TITLE
No content in File Manager

### ISSUE THREAD

**Issue by Svardsten53** [Nachtzuster/BirdNET-Pi#3]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**
When starting File Manager in Tools menu only user root is shown, nothing in underlying tree.

**To Reproduce**
Tools - File Manager

**Expected behavior**
I would like to see all folders and files in my installation.

**Screenshots**

**Additional context**

**Your build**
Raspberry Pi 4B 8GB wiht Bookworm Lite 64 bit

**Code or log snippets**

**Comment by Nachtzuster** [comment]
Thanks for reporting.
I pushed a fix, should work now now.
Please run Update

Thanks!

**Comment by Svardsten53** [comment]
It works now. Thank you!
