### ISSUE TITLE
Settings Login Issue

### ISSUE THREAD

**Issue by Searchyourname** [Nachtzuster/BirdNET-Pi#4]
Having a strange problem. Birdnet.conf has my password saved but the default "birdnet" no password is what works to get to "tools". When I click "settings" it prompts me for another login and neither the default login nor my set password works.

Any ideas? 

EDIT: I ran the update_birdnet.sh script through ssh and it seemed to fix everything. I think ...

**Comment by Nachtzuster** [comment]
Thanks for reporting, sounds like it might be a permissions issue maybe

**Comment by Nachtzuster** [comment]
I can't reproduce unfortunatly
