### ISSUE TITLE
Issue with German location code

### ISSUE THREAD

**Issue by R3tr0BoiDX** [Nachtzuster/BirdNET-Pi#56]
![image](https://github.com/Nachtzuster/BirdNET-Pi/assets/11410005/126ba4e3-60fa-4537-9367-211f8173439e)

**Comment by R3tr0BoiDX** [comment]
This is from the log online btw, in case that wasn't obvious, heh

**Comment by Nachtzuster** [comment]
This seems to be an fairly common issue issue, according to Google. Not quite sure what the 'correct' fix would be, but for now, just deleting the incorrect `/etc/timezone` should 'fix' it

**Comment by lloydbayley** [comment]
I've given this a great deal of thought too. It's a really tricky one. It poses the question "Can a 'complete fix' be implemented?" There are so many ways it could be 'corrupted' by the insertion of multiple timezones that it's really down to the user to control. It's hard for BirdNet-Pi to be responsible for the OS settings unless it has the audacity to check and override them, which is a big thing. On one hand, I feel that the OS settings are the user responsibility and on the other hand, I'm wondering if there might be a check by BirdNet-Pi to alert the user to the potential problem. The underlying question is, how far does the responsibilty stretch?

**Comment by Nachtzuster** [comment]
@R3tr0BoiDX  I pushed a fix for this, setting the timezone should be fine now

**Comment by R3tr0BoiDX** [comment]
> @R3tr0BoiDX I pushed a fix for this, setting the timezone should be fine now

awesome, thanks!
