### ISSUE TITLE
BirdWeather "email Tim" registration method is out of date

### ISSUE THREAD

**Issue by scruss** [Nachtzuster/BirdNET-Pi#67]
**Describe the bug**
You can get a BirdWeather ID yourself, and you no longer need to send email to make it happen.

**To Reproduce**
1. Go to "Tools", "BirdWeather", and click on *Email Tim to request a BirdWeather ID*
2. Compose and send email
3. wait …
4. wait …
5. Eventually get an email that says *You can now use our automated form to create your BirdWeather ID."

Please update the registration method. Full text of the email follows:

> Hi!
> 
> You can now use our automated form to create your BirdWeather ID.
> 
> You’ll first need to create an account - https://app.birdweather.com/login
> 
> Once that’s done - you can go to - https://app.birdweather.com/account/stations
> 
> Make sure that the Latitude and Longitude match what is in your BirdNET-Pi configuration.
> 
> NOTE - by using your BirdWeather ID - you are consenting to sharing your soundscapes and detections with BirdWeather.
> 
> Cheers!
> 
> -Tim
> 
> Founder - BirdWeather

**Comment by lloydbayley** [comment]
#68

**Comment by Nachtzuster** [comment]
@scruss , @lloydbayley  merged just now, Thanks!
