### ISSUE TITLE
User friendly $listenurl links in notifications 

### ISSUE THREAD

**Issue by craigusus** [Nachtzuster/BirdNET-Pi#80]
**Describe the enhancement**
Rather than having the full URL to the recording in the notification (discord). It would be nice to have it say 'Listen Here', or 'Listen'

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Tools > Settings'
2. Scroll down to 'Notifications'
3. Add '$listenurl' to the 'Notification Body:' field

**Expected behaviour**
From this:
<img width="373" alt="image" src="https://github.com/Nachtzuster/BirdNET-Pi/assets/6324863/f2944759-6392-4ced-9053-cef8d3b1b006">
To this:
<img width="369" alt="image" src="https://github.com/Nachtzuster/BirdNET-Pi/assets/6324863/66af2a2f-c726-4986-9fdd-2c2712902996">

**Your build**
Raspberry Pi 5 8GB
Latest (it has only been running for 2 days 😄)

**Comment by lloydbayley** [comment]
Looks like #88 is a successful fix. Tested here ok on my Dev install.
