### ISSUE TITLE
Changing bird species gives error

### ISSUE THREAD

**Issue by Hiemstra87** [Nachtzuster/BirdNET-Pi#81]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**
When i try to change the species it throws an error. (See screenshot). "The first argument should be a starting with the common name of the bird and finish with mp3!, Instead, it is : Porseleinhoen***.wav<br>"
It does not change the species of the recording.

**To Reproduce**
Go to recordings -> by species -> -bird-
Tap bird icon
Choose new species
Confirm the "are you sure"
Error

**Expected behavior**
no error and change of species.

**Screenshots**
![Screenshot_20240601-213604](https://github.com/Nachtzuster/BirdNET-Pi/assets/145980686/994087a7-b44e-45b9-b8a4-bb0062ffac5f)

**Additional context**
actions from a Google Pixel phone on Chrome browser:
version 125.0.6422.146
com.android.chrome

**Your build**
Birdnet-PI build on RasPI 5, additional install of Cloudflared.

**Code or log snippets**
"The first argument should be a starting with the common name of the bird and finish with mp3!, Instead, it is : Porseleinhoen***.wav<br>"

</details>

**Comment by alexbelgium** [comment]
Thanks for reporting! Indeed i considered only files saved as .mp3, I didn't knew it was possible for other formats. I'll make an update proposal to the code

**Comment by Hiemstra87** [comment]
Wow that's a quick reply! Thanks!

**Comment by alexbelgium** [comment]
Well there was a lack of goals in the Champions league final so I was a bit idle - this has changed however since ;)

**Comment by Hiemstra87** [comment]
Yeah, bit of a disappointment Dortmund didn't win though

**Comment by alexbelgium** [comment]
Indeed... Rm has enough trophies on their shelves... And I had the luxury of being perfectly neutral in this final

**Comment by lloydbayley** [comment]
Nice bug-squash! I must admit, I, too, had forgotten about the possibility of changing format. I never really occurred to me to alter it but I guess when you have ffmpeg at your disposal, the world is your oyster! :)
Bonne Chance & Viel Glück to you both!

**Comment by Hiemstra87** [comment]
Nice quick fix, just tested it, works like a charm. You're making a lot of people happy with this feature.

**Comment by lloydbayley** [comment]
He can't help it....He's a people-pleaser....
