### ISSUE TITLE
Caddy v2.8.2 breaks current and new installations

### ISSUE THREAD

**Issue by craigusus** [Nachtzuster/BirdNET-Pi#84]
**Describe the bug**
I've been having stability issues with my Pi5 install, so I tried an apt update/upgrade as I know some of my other Pis have had kernel/pi firmware updates. One of the updates was to caddy. After the update I had no access to the web interface of my BirdNET-Pi. But the Pi4 I have on test in my shed, is working fine.

**To Reproduce**
1. Log in via ssh
2. Run `sudo apt update && sudo apt full-upgrade -y`

Also
1. Clean install from scratch
2. Run `sudo apt update && sudo apt full-upgrade -y`
3. Run BirdNET-Pi install script

**Expected behavior**
Caddy service to not fail

**Screenshots**
Fresh install Pi5 (broken):
<img width="850" alt="image" src="https://github.com/Nachtzuster/BirdNET-Pi/assets/6324863/279f5d19-5d49-4baa-ab7a-36ba4d62f641">
Test Pi4 (built yesterday, 1st June):
<img width="817" alt="image" src="https://github.com/Nachtzuster/BirdNET-Pi/assets/6324863/3365b691-acab-4105-bf83-0b408ce5ae11">

**Your build**
Pi5 8GB and Pi4 1GB

**Comment by Aixsponsa** [comment]
I do not have anything to add besides that my web interface is also inaccessible today.

**Comment by Swiftnesses** [comment]
This is fixed, as 2.8.4 has been released. Rerunning the install should do it.

**Comment by craigusus** [comment]
@Swiftnesses Yes, this seems to have fixed it now. Thanks for the update.
