### ISSUE TITLE
Issue with Unsupported Characters in Daily Charts and Spectrograms

### ISSUE THREAD

**Issue by kyjibato** [Nachtzuster/BirdNET-Pi#93]
Thank you for the incredible work on this project. 
While setting up the system in Japanese via Tools->Settings->Localization, I noticed that the species names in the Daily charts appeared as unsupported characters.

To address this, I installed the Noto Sans font from [here](https://fonts.google.com/noto/specimen/Noto+Sans+JP) into `homepage/static`. Additionally, I replaced `Roboto Flex` with `Noto Sans CJK JP` at line 158 in `scripts/daily_plot.py`, which successfully resolved the display issue for the Daily charts. However, the species names at the top of the spectrograms still appear as question marks. It seems this issue stems from the `get_safe_title(title)` function in `scripts/utils/reporting.py` at line 20, which converts UTF-8 characters to ASCII. I would appreciate if you could investigate and provide a solution for this.

Default font (Roboto Flex)
![Combo-2024-06-08](https://github.com/Nachtzuster/BirdNET-Pi/assets/109225406/ec42392d-e7eb-43dd-8107-ec10e317196d)
Font changed to Noto Sans
![Combo-2024-06-09](https://github.com/Nachtzuster/BirdNET-Pi/assets/109225406/12a565d7-4942-440c-8d6d-a6f56b034661)
Spectrograms
<img width="342" alt="スクリーンショット 2024-06-09 午後8 58 09" src="https://github.com/Nachtzuster/BirdNET-Pi/assets/109225406/2804240e-4ba8-4ae3-a651-417ff3d31188">

**Comment by Nachtzuster** [comment]
Thanks for reporting.

So there seem to be two separate but related issues:
- daily_plot.py: should be fixable, thanks for the details
- spectrograms: this is harder: get_safe_title() existes because `sox`, the tool that creates the spectrogram does not support non-ascii text, see https://sourceforge.net/p/sox/feature-requests/214/

**Comment by Nachtzuster** [comment]
> I installed the Noto Sans font from [here](https://fonts.google.com/noto/specimen/Noto+Sans+JP)

font noob question: Is there a particular reason to pick this specific font?

**Comment by kyjibato** [comment]
Thank you for your reply. The reason I chose Noto Sans is because it supports CJK (Chinese, Korean, and Japanese) characters, has a clear licensing structure, and is created by Google, similar to Roboto.
https://github.com/notofonts/noto-cjk/tree/main/Sans

**Comment by Nachtzuster** [comment]
@kyjibato could you update to see if it works for you now?

**Comment by Nachtzuster** [comment]
@kyjibato could you open another issue for the spectrograms?
we might have to re-implement that with python/mathplotlib

**Comment by kyjibato** [comment]
The recent fix you implemented for the issue has worked perfectly in displaying Japanese characters. I truly appreciate your quick and effective response. I will open another issue.
![Combo-2024-06-15](https://github.com/Nachtzuster/BirdNET-Pi/assets/109225406/0d639075-7354-4fb1-8a0f-f6c3543e62e5)

**Comment by Nachtzuster** [comment]
@kyjibato so you have a BirdNET-Pi instance actually running in Japan?

**Comment by kyjibato** [comment]
@Nachtzuster Yes, I run my BirdNET-Pi in Japan. This is my station https://app.birdweather.com/stations/4987
