### ISSUE TITLE
BUG - Species List Tester doesnt work anymore -> thisrun.txt got removed

### ISSUE THREAD

**Issue by MueJosh** [Nachtzuster/BirdNET-Pi#94]
**Describe the bug**
Fresh Install -> Species List Tester does not work because "thisrun.txt" does not exist anymore (removed in a update)

**To Reproduce**
1. Go to "Tools" -> "Settings" -> "Model"
2. Click on "Species List Tester" 
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen. - You know what to expext - it works on all of my old installs 
![working](https://github.com/mcguirepr89/BirdNET-Pi/assets/145150281/752b8d06-ecf2-4284-8508-29916c9d0fa3)

**Your build**
Pi 02W, 2GiB Swap
![info](https://github.com/Nachtzuster/BirdNET-Pi/assets/145150281/fa391dc0-cbc8-4c9e-896b-3a3d94e1f0bb)

**Code or log snippets**
```
Traceback (most recent call last):
  File "/home/USERNAME/BirdNET-Pi/scripts/species.py", line 100, in 
    lat = str(str(str([i for i in this_run if i.startswith('LATITUDE')]).split('=')[1]).split('\\')[0])
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
![not_working](https://github.com/mcguirepr89/BirdNET-Pi/assets/145150281/dfb0b15b-6651-45b4-a375-cabb2269375c)

**Comment by Nachtzuster** [comment]
thanks for reporting!
I must have had a bad day when I did that cleanup.

I pushed a fix, could you try?

**Comment by MueJosh** [comment]
> thanks for reporting!
> 
> I must have had a bad day when I did that cleanup.
> 
> 
> 
> I pushed a fix, could you try?

Thanks! 

It works again 👍
