### ISSUE TITLE
Feat proposal : apprise alert if analysis service stopped ?

### ISSUE THREAD

**Issue by alexbelgium** [Nachtzuster/BirdNET-Pi#97]
Proposal : use apprise to send an alert if services are failing

Implementation : cron job to periodically monitor if "birdnet_analysis" service is active, and send a telegram alert if not ? should it also monitor recording (although recording can be paused to accomodate backlogs)

Usercase : in case the service stops for whatever reason, the user is alerted. Could be especially useful for remote systems.

Counterargument : only works if the system is on ; an external healthcheck could be even more efficient (publish services status as a json in an endpoint) ?

**Comment by Nachtzuster** [comment]
not sure if it would scratch your itch, but there is a heartbeat: https://github.com/Nachtzuster/BirdNET-Pi/blob/0a09e73549c0b0d4f5effbeb7088a0fcf7eb36fa/scripts/install_config.sh#L246
```
## HEARTBEAT_URL is a location to ping every time some analysis is done
## no information is sent to the the URL, its a heart beat to show that the
## analysis is continuing

HEARTBEAT_URL=
```

**Comment by alexbelgium** [comment]
Thanks! I hadn't noticed it. Then indeed it is probably better to use an existing feature rather than complexifying things.
